Update kotlin monorepo to v1.9.0-RC (#755)
[![Mend
Renovate](https://app.renovatebot.com/images/banner.svg)](https://renovatebot.com)

This PR contains the following updates:

| Package | Change | Age | Adoption | Passing | Confidence |
|---|---|---|---|---|---|
| [org.jetbrains.kotlin.plugin.noarg](https://kotlinlang.org/)
([source](https://togithub.com/JetBrains/kotlin)) | `1.9.0-Beta` ->
`1.9.0-RC` |
[![age](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlin.plugin.noarg/1.9.0-RC/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlin.plugin.noarg/1.9.0-RC/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlin.plugin.noarg/1.9.0-RC/compatibility-slim/1.9.0-Beta)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlin.plugin.noarg/1.9.0-RC/confidence-slim/1.9.0-Beta)](https://docs.renovatebot.com/merge-confidence/)
|
| [org.jetbrains.kotlin.jvm](https://kotlinlang.org/)
([source](https://togithub.com/JetBrains/kotlin)) | `1.9.0-Beta` ->
`1.9.0-RC` |
[![age](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlin.jvm/1.9.0-RC/age-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![adoption](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlin.jvm/1.9.0-RC/adoption-slim)](https://docs.renovatebot.com/merge-confidence/)
|
[![passing](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlin.jvm/1.9.0-RC/compatibility-slim/1.9.0-Beta)](https://docs.renovatebot.com/merge-confidence/)
|
[![confidence](https://badges.renovateapi.com/packages/maven/org.jetbrains.kotlin.jvm/1.9.0-RC/confidence-slim/1.9.0-Beta)](https://docs.renovatebot.com/merge-confidence/)
|

---

### ⚠ Dependency Lookup Warnings ⚠

Warnings were logged while processing this repo. Please check the
Dependency Dashboard for more information.

---

### Release Notes

<details>
<summary>JetBrains/kotlin</summary>

###
[`v1.9.0-RC`](https://togithub.com/JetBrains/kotlin/releases/tag/v1.9.0-RC):
Kotlin 1.9.0-RC

##### Changelog

##### Backend. Wasm

- [`KT-58188`](https://youtrack.jetbrains.com/issue/KT-58188) Restore
binary compatibility of
PlatformDiagnosticSuppressor.shouldReportUnusedParameter
- [`KT-58293`](https://youtrack.jetbrains.com/issue/KT-58293) Wasm:
ReferenceError: e is not defined in kotlin.test.jsThrow
- [`KT-58931`](https://youtrack.jetbrains.com/issue/KT-58931) Wasm tests
are failing to start on Kotlin 1.9.0-Beta

##### Compiler

##### Fixes

- [`KT-58621`](https://youtrack.jetbrains.com/issue/KT-58621) K2:
Private class shadows public function defined in the same package
- [`KT-59102`](https://youtrack.jetbrains.com/issue/KT-59102) K2:
constant evaluator does not provide Long type on shl
- [`KT-59079`](https://youtrack.jetbrains.com/issue/KT-59079) "AE:
SyntheticAccessorLowering should not attempt to modify other files!"
with callable reference to constructor with value class parameter
- [`KT-58787`](https://youtrack.jetbrains.com/issue/KT-58787) KAPT:
"NullPointerException: null cannot be cast to non-null type" with
delegate
- [`KT-58837`](https://youtrack.jetbrains.com/issue/KT-58837) Partial
linkage fails to report any compiler message on Windows when launched
through Gradle plugin
- [`KT-59030`](https://youtrack.jetbrains.com/issue/KT-59030) \[PL]
Workaround for broken `@Deprecated` annotations in c-interop KLIBs
- [`KT-58618`](https://youtrack.jetbrains.com/issue/KT-58618) K2: Local
property delegates cannot infer generic return type
- [`KT-58897`](https://youtrack.jetbrains.com/issue/KT-58897) K2: False
positive unresolved reference with same-named enum class and its entry
- [`KT-56927`](https://youtrack.jetbrains.com/issue/KT-56927) Enum with
secondary constructor can't be compiled with K2 using JS/Native backend
- [`KT-57570`](https://youtrack.jetbrains.com/issue/KT-57570) Remove
source code excerpts from platform type nullability assertion exceptions
- [`KT-52774`](https://youtrack.jetbrains.com/issue/KT-52774) Resolve
unqualified enum constants based on expected type

##### IDE. Gradle Integration

- [`KT-59034`](https://youtrack.jetbrains.com/issue/KT-59034) MPP build
failed with "Factory type is not known for plugin variants" in kt-231-\*

##### JavaScript

- [`KT-58570`](https://youtrack.jetbrains.com/issue/KT-58570) KJS: ES6
classes + PL throw java.lang.NullPointerException
- [`KT-58835`](https://youtrack.jetbrains.com/issue/KT-58835) K2/JS: Fix
incremental compilation klib tests
- [`KT-58794`](https://youtrack.jetbrains.com/issue/KT-58794) KJS / K2:
Assertion failed with Space build

##### Libraries

- [`KT-58985`](https://youtrack.jetbrains.com/issue/KT-58985) Update
KClass.isData KDoc
- [`KT-58276`](https://youtrack.jetbrains.com/issue/KT-58276) Deprecate
redundant public declarations in kotlin.native.concurrent

##### Native. ObjC Export

- [`KT-58839`](https://youtrack.jetbrains.com/issue/KT-58839) K/N:
Exception during HiddenFromObjC marked class extension function
compiling

##### Tools. Compiler plugins. Serialization

- [`KT-58918`](https://youtrack.jetbrains.com/issue/KT-58918)
Serialization: NPE at run time obtaining a serializer for a sealed class
with a generic self-referencing property
- [`KT-58954`](https://youtrack.jetbrains.com/issue/KT-58954)
Serialization: NPE at run time when accessing a delegating property of a
deserialized object
- [`KT-59113`](https://youtrack.jetbrains.com/issue/KT-59113)
Serialization: NPE at run time when accessing a delegating property of a
deserialized object
- [`KT-57647`](https://youtrack.jetbrains.com/issue/KT-57647)
Serialization: "IllegalAccessError: Update to static final field" caused
by serializable value class

##### Tools. Gradle

- [`KT-59256`](https://youtrack.jetbrains.com/issue/KT-59256)
\[1.9.0-Beta] ServiceLoader does not pick up classes defined in the same
project
- [`KT-58662`](https://youtrack.jetbrains.com/issue/KT-58662) Gradle 8.1
+ Configuration Cache: custom values data is missing from build report
- [`KT-59063`](https://youtrack.jetbrains.com/issue/KT-59063) Explicit
API mode broken in Kotlin 1.9.0-Beta
- [`KT-59191`](https://youtrack.jetbrains.com/issue/KT-59191) Actual
compilation failure exception might be hidden in the case of a Kotlin
daemon crash
- [`KT-59056`](https://youtrack.jetbrains.com/issue/KT-59056)
FreeCompilerArgs options added using 'subprojects' extension override
module-level freeCompilerArgs options
- [`KT-55740`](https://youtrack.jetbrains.com/issue/KT-55740) Gradle 8:
Listener registration using Gradle.addBuildListener() has been
deprecated
- [`KT-58251`](https://youtrack.jetbrains.com/issue/KT-58251) Build
Statistics. Kotlin-specific tags are missing in build scans if projects
use Gradle 8+
- [`KT-58916`](https://youtrack.jetbrains.com/issue/KT-58916)
\[1.9.0-Beta] PLUGIN_CLASSPATH_CONFIGURATION_NAME and
NATIVE_COMPILER_PLUGIN_CLASSPATH_CONFIGURATION_NAME should stay public
or offer an alternative API
- [`KT-58869`](https://youtrack.jetbrains.com/issue/KT-58869) K2,
Gradle: Improve message "100% (2/2) tasks have compiled with Kotlin 2"

##### Tools. Gradle. JS

- [`KT-59116`](https://youtrack.jetbrains.com/issue/KT-59116) K/JS npm
dependcies are not resolved properly on Kotlin 1.9
- [`KT-58970`](https://youtrack.jetbrains.com/issue/KT-58970)
browserTest gradle task fails if karma is used and gradle configuration
cache is enabled
- [`KT-59004`](https://youtrack.jetbrains.com/issue/KT-59004) Kotlin JS
1.9.0-Beta, yarn.lock is unstable in multi module project

##### Tools. Gradle. Multiplatform

- [`KT-57903`](https://youtrack.jetbrains.com/issue/KT-57903) Prepare
for migration to the pluggable android target plugin
- [`KT-58661`](https://youtrack.jetbrains.com/issue/KT-58661) KGP:
KotlinJvmTarget: Implement 'run' carrier task
- [`KT-59055`](https://youtrack.jetbrains.com/issue/KT-59055)
KotlinJvmRun not respecting jvmToolchain setting

##### Tools. Gradle. Native

- [`KT-57823`](https://youtrack.jetbrains.com/issue/KT-57823)
KotlinNativeCompileOptions.moduleName value is ignored and replaced with
the default one if to set up using compilations
- [`KT-58838`](https://youtrack.jetbrains.com/issue/KT-58838)
KGP/Multiplatform: 1.9.0-Beta with custom cinterops:
IllegalStateException: Could not create domain object 'jni'
(DefaultCInteropSettings)

##### Tools. Incremental Compile

- [`KT-58986`](https://youtrack.jetbrains.com/issue/KT-58986) New IC:
ISE "The following LookupSymbols are not yet converted to
ProgramSymbols: LookupSymbol(name=$$delegatedProperties, ...)"

##### Tools. Parcelize

- [`KT-59112`](https://youtrack.jetbrains.com/issue/KT-59112) K2:
"IllegalStateException: Function has no body with `@Parcelize`" on
nested sealed class hierarchies

##### Checksums

| File | Sha256 |
| --- | --- |
| kotlin-compiler-1.9.0-RC.zip |
d00312caa89de1dd3f62d80d5b31724efc333101616ba4a22caf4458862315e7 |
| kotlin-native-linux-x86\_64-1.9.0-RC.tar.gz |
2dc30ef2b73bcc561decd5efc7b78b7431cfe2fb982c471baaa6762c5022ce5a |
| kotlin-native-macos-x86\_64-1.9.0-RC.tar.gz |
a4b9b2dbb6793ee6857e3cbdecceb2d972aba1c1055e64bd7cce90fe0c776afc |
| kotlin-native-macos-aarch64-1.9.0-RC.tar.gz |
1ca609007c2cbc587b4ce5e689064867ec18a377ce0ca24a777edf8d74cb7df9 |
| kotlin-native-windows-x86\_64-1.9.0-RC.zip |
b3e35851992132fea2608fa6be87f0fda4b613bca2a4417e5dc3bf1509128a2d |

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined),
Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you
are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the
rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about these
updates again.

---

- [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check
this box

---

This PR has been generated by [Mend
Renovate](https://www.mend.io/free-developer-tools/renovate/). View
repository job log
[here](https://developer.mend.io/github/ZacSweers/CatchUp).

<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzNS4xMzEuMCIsInVwZGF0ZWRJblZlciI6IjM1LjEzMS4wIiwidGFyZ2V0QnJhbmNoIjoibWFpbiJ9-->

Co-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>