Switch Markdown to be inline class
Note that this doesn't work currently because kapt generates an invalid stub:

```
e: /Users/pandanomic/dev/android/personal/CatchUp/app/build/tmp/kapt3/stubs/debug/io/sweers/catchup/util/Markdown.java:18: error: modifier static not allowed here
public static final class Markdown {
```

```
package io.sweers.catchup.util;

import in.uncod.android.bypass.Bypass;
import in.uncod.android.bypass.style.TouchableUrlSpan;
import android.content.res.ColorStateList;
import android.os.Build;
import android.text.Html;
import android.text.SpannableString;
import android.text.SpannableStringBuilder;
import android.text.Spanned;
import android.text.TextUtils;
import android.text.style.URLSpan;
import android.text.util.Linkify;
import android.widget.TextView;
import androidx.annotation.ColorInt;

@kotlin.Metadata(mv = {1, 1, 11}, bv = {1, 0, 2}, k = 3, xi = 2)
public static final class Markdown {

    @org.jetbrains.annotations.NotNull()
    public static final io.sweers.catchup.util.Markdown box(@org.jetbrains.annotations.NotNull()
    java.lang.String v) {
        return null;
    }
}
```